site_name: frontend-py
site_description: 'Frontend.swift: A test site to see how this will look in production'
site_author: 'Simon Rydell'
site_url: 'https://Tolc-Software.github.io/tolc/'
docs_dir: 'public'
strict: true
nav:
  - objc:
    - Quickstart: 'quickstart.md'
    - Conversions: 'conversions.md'
    - Examples: 'examples.md'
    - Naming Convention: 'naming_convention.md'
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - tables
theme:
  name: material
  font:
    text: IBM Plex
    code: IBM Plex mono
  palette:
    primary: black
    accent: deep purple
extra:
  generator: false
